[F] Fix homepage & aboutpage doesnot display English content
one-among-us/web pull request #25
Opened 2023-06-22 10:25 UTC by LS-KR

还是手译的（塑料英语）

2023-06-25 04:03 UTC, BeiyanYunyi approved these changes

2023-06-30 10:12 UTC, hykilpikonna commented on src/App.vue
> +        }
在 Vue 里面用 querySelector 手动设置内容不太好... 改了一下改成用一个变量定义多语言文字了

2023-06-30 10:54 UTC, hykilpikonna commented
改了一下切换语言按钮

![image](https://github.com/one-among-us/web/assets/22280294/a80ce514-ed8f-40a2-b195-bbc931c4918a)

2023-06-30 11:25 UTC, hykilpikonna commented
本地化了一些翻译细节，整体还不错。

（还没改完，好累呜呜

2023-06-30 23:13 UTC, LS-KR commented
把原文的`小册子`指向的url改了一下  

（以及为什么是个了解更多页面（气鼓鼓

2023-07-09 14:45 UTC, Aquaticat commented on src/logic/config.ts
> +        "nav_req_anonymous": "Anonymous is available if you don't want to leave a nickname.",
"nav_req_anonymous": "(You don't have to leave a nickname.)",

2023-07-09 14:46 UTC, Aquaticat commented on src/assets/home-top.en.md
> **Warning**  
> 
> The operation of One Among Us is currently in a critical period. We have received numerous reports about suicides. If you feel uncomfortable while browsing the page of the deceased, please exit immediately and seek help from doctors, the community, and local suicide intervention agencies if necessary. And, please try to help others while ensuring your mental health.  
> 
> Although One Among Us does not currently have suicide prevention capabilities, if you really need help, you can send messages to our official Twitter account [@oneamong_us](https://twitter.com/oneamong_us) or send an email to [info@one-among.us](mailto:info@one-among.us). We will provide simple assistance or refer you to other hospitals or social agencies that can handle it. Please note that neither of these options is monitored 24/7.  
> 
> Let us stand together and survive, until the dark clouds disperse.  
> 
> **Suicide Prevention organizations**  
>  
> (Canada/US) [Trans Lifeline](https://translifeline.org/) - Canada (877) 330-6366, US (877) 565-8860  

I always remember a sentence in "Coco": Death is not the end of life, but oblivion is. Those who have left us, perhaps somewhere, are whispering to us: "Please don't forget me."    

The traces of existence may fade with time. Old photos can lose their color, and social media accounts may disappear as the internet change. Yet, the things that influence us, that bring them back to us, are not always those that physically exist. When we suddenly recall conversations we had or places we've been, the gates of memory swing open, and their voices and smiles are as vivid as ever.  

Many of us did not meet because of geographical or professional ties, but because of our shared circumstances in life. We've come to this place we call "community".
We may have never met in person and may live thousands of miles apart, crossing the boundaries of language and nationality.
Perhaps I can't even verify their "real existence". But how would we define the boundary between reality and illusion?
Even if we are not their family members, friends, or lovers in the real world, can that friendship or affection be easily denied?
When they pass away, when that avatar never goes online again, I always have a selfish desire to find a place to commemorate them, to let them continue to exist and accompany us forward.  

That's why we built this website. Those who left our lives prematurely for various reasons, those transgender individuals and our cisgender allies, are still one of us (one among us), silently caring for and accompanying us, empowering us, and giving us the courage to live on and move forward.
Perhaps the name written on the monument in reality is not what they preferred, and it may not reflect their true identity, but we can still realize all of this in our own memorial.  

We shall meet again in a place where there is no darkness.

2023-07-09 14:47 UTC, Aquaticat commented on src/assets/home-bottom.en.md
```markdown
# Stopping Transphobic Violence

The [Transgender Factsheet](https://www.unfe.org/wp-content/uploads/2019/03/Transgender_Factsheet_English.pdf) from the UN Human Rights Office states that “Trans people in all parts of the world are at heightened risk of violence, harassment and discrimination.
Human rights violations range from bullying and verbal abuse, to denial of healthcare, education, work and housing, to criminalization, arbitrary arrest and detention, violence, assault, torture, rape and murder.
Exposure to these and related abuses may be further exacerbated by other factors, such as age, ethnicity, occupation, socio-economic class and disability."  

In addition to advocating for a better social environment, there are many things that an individual can do:

- Understand the issues and concerns of transgender individuals' life experiences.  
- Address them with their preferred pronouns, genders, and names.  
- Take the initiative to say no when you witness any form of stigma, discrimination, and violence against transgender people.  

# How to Contribute

You can edit or create commemorative entries by submitting Pull Requests through our [GitHub repository](https://github.com/one-among-us/data).
When the Pull Request is approved and merged by the maintainer, the new entry will be displayed on the website.  

If you're unsure how to proceed, please feel free to [Contact Us](/about).
```

2023-07-09 14:49 UTC, Aquaticat requested changes
除了这个 comment 以外，还有三个 pending comment。

https://github.com/one-among-us/web/pull/25/files#r1257495506
https://github.com/one-among-us/web/pull/25/files#r1257495356
https://github.com/one-among-us/web/pull/25/files#r1257495231

2023-07-09 14:49 UTC, Aquaticat commented on src/assets/about.en.md
```markdown
# Contact US

This site is currently maintained by a team of volunteers of a non-profit organization. Source code is on [One Among Us GitHub organization page](https://github.com/one-among-us).  

- You can send email to **info@one-among.us** to contribute or put forward criticism and suggestions.
- You can also contact us through opening a GitHub issue or Pull request.
- Our [Twitter account](https://twitter.com/oneamong_us) welcomes private messages and comments.
```

2023-07-10 00:06 UTC, LS-KR commented
> 除了这个 comment 以外，还有三个 pending comment。
> 
> https://github.com/one-among-us/web/pull/25/files#r1257495506 https://github.com/one-among-us/web/pull/25/files#r1257495356 https://github.com/one-among-us/web/pull/25/files#r1257495231

已经修改
以及妳似乎忘记了所有换行前面的两个空格qwq（

2023-07-10 00:15 UTC, LS-KR commented
这回是真改过来了qwq（

2023-07-10 00:50 UTC, sauricat commented
你们觉得咋样？能上线就先合了，剩下的慢慢改。

2023-07-10 01:14 UTC, Aquaticat commented
我觉得可以。

2023-07-10 01:54 UTC, LS-KR commented
咱想不出需要添加/修改的新点子了qwq

2023-07-10 13:12 UTC, merged